### ISSUE TITLE
Update script only updates the direct dependencies

### ISSUE THREAD

**Issue by Eduardo-Morales-Alberti** [Metadrop/scripthor#31]
Update script only updates the direct dependencies, maybe it should check also if it has drupal modules to update, it does not care if is direct or not. Filtered for example by drupal/[NAME], they are not libraries, they are modules that need to be updated.

**Comment by jorgetutor** [comment]
Current behavior:

Package A requires package B.

If there is an update in A and B: A + B are updated
If there is only an update in B: B is not updated because of the D (direct rule) "composer show -omND"

The script updates also the dependencies but only when there is an update on the package that requires them:

composer update $c --with-dependencies

If we want to change this approach (I agree) I think it should be done at Composer level as the need could be the same for a Drupal module or Library dependency.

Options: 

- Remove the "D" so everything gets updated
- Expose it as a cli option

What do you think?

**Comment by Eduardo-Morales-Alberti** [comment]
Close, implemented on https://github.com/Metadrop/scripthor/commit/a4d41af6982b0a32db86aea00c2f74a90e706aee
